### ISSUE TITLE
Novation SL49 Compact support

### ISSUE THREAD

**Issue by abulka** [git-moss/SLMkII4Bitwig#2]
Quite a few things work fine also on my Novation SL49 Compact but some things don't. 
Any plans to one day support the Novation SL49 Compact fully too?
Thanks

**Comment by git-moss** [comment]
Sorry, no. I do not own any of that range. But since these a pretty simple devices you could use e.g. Thomas' midi learn script:
http://www.bitwig.com/en/community/control_scripts/generic/toms_generic_midilearn/toms_generic_midilearn.html
