### ISSUE TITLE
Problems with track navigation and collapsed track folders?

### ISSUE THREAD

**Issue by adamlwatson** [git-moss/SLMkII4Bitwig#4]
Heya @git-moss,

I'm noticing that when I have track groups collapsed, the track navigation using the SL MkI breaks. If you scroll to the next bank of tracks and attempt to select one, the selection reverts to the first bank.

Haven't looked at the code yet, but will. Just wondering if you see the same problem on the MkII ?

Cheers,
Adam

**Comment by git-moss** [comment]
Since the Remote script uses a flat track representation it might look weird when you use it. The tracks are selected inside the group but you do not see it when they are closed. Besides that it looks OK to me.
