### ISSUE TITLE
Remote SL2 Mk2 script version 4 doesn't work on OSX 10.11.6

### ISSUE THREAD

**Issue by ice1x** [git-moss/SLMkII4Bitwig#5]
Remote SL2 Mk2 script version 4 doesn't work on OSX 10.11.6

Host: OSX 10.11.6 + Bitwig 1.3.15
Test-case:
1.)Download SL2 Mk2 script version 4 from http://www.mossgrabers.de/Software/Bitwig/SLMkII4BitwigV1.zip

2.)Move files from archive to Bitwig folder/Controller\ Scripts/
3.)Run Bitwig, try to add Novation/SL2*

>Expected:
Device is present in Novation/list

>Actual:
No SL2* devices in list 

>Info:
No such problem with 3.* version of script

**Comment by git-moss** [comment]
#4.00 Requires Bitwig 2.0. See the changelist.
